language: generic
sudo: 'required'
services:
  - docker 

before_install: 
  - docker build -t protickr/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true protickr/react-test npm run test

after_success: 
  - docker build -t protickr/multi-client ./client
  - docker build -t protickr/multi-nginx ./nginx
  - docker build -t protickr/multi-server ./server
  - docker build -t protickr/multi-worker ./worker
