language: generic
sudo: 'required'
services:
  - docker 

before_install: 
  - docker build -t protickr/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true protickr/react-test npm run test

after_success: 
  - docker build -t protickr/multi-client ./client
  - docker build -t protickr/multi-nginx ./nginx
  - docker build -t protickr/multi-server ./server
  - docker build -t protickr/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # after building all images we need to push them to docker hub
  - docker push protickr/multi-client
  - docker push protickr/multi-nginx
  - docker push protickr/multi-server
  - docker push protickr/multi-worker